project:
  type: website

website:
  title: "SIMLAR"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: queries.qmd
        text: Queries
      - href: flow.qmd
        text: Flowcharts
        

format:
  html:
    theme: solar
    css: styles.css
    toc: true



